import { FormType } from "../../admin/page";

export const MCC_FORMS: Record<string, FormType> = {
  "5411": {
    id: "form_5411",
    fields: [
      {
        id: "field_1",
        type: "text",
        label: "Prénom",
        name: "firstName",
        placeholder: "Votre prénom",
        required: true,
        options: [],
      },
      {
        id: "field_2",
        type: "text",
        label: "Nom",
        name: "lastName",
        placeholder: "Votre nom",
        required: true,
        options: [],
      },
      {
        id: "field_3",
        type: "text",
        label: "Adresse de livraison",
        name: "deliveryAddress",
        placeholder: "Votre adresse de livraison",
        required: true,
        options: [],
      },
      {
        id: "field_4",
        type: "text",
        label: "Numéro de téléphone",
        name: "phoneNumber",
        placeholder: "Votre numéro de téléphone",
        required: false,
        options: [],
      },
      {
        id: "field_5",
        type: "email",
        label: "Email",
        name: "email",
        placeholder: "Votre adresse email",
        required: false,
        options: [],
      },
      {
        id: "field_6",
        type: "select",
        label: "Méthode de paiement",
        name: "paymentMethod",
        placeholder: "Sélectionnez une méthode de paiement",
        required: false,
        options: ["Carte bancaire", "Espèces", "Chèque", "Virement"],
      },
    ],
  },
  "5812": {
    id: "form_5812",
    fields: [
      {
        id: "field_1",
        type: "text",
        label: "Prénom",
        name: "firstName",
        placeholder: "Votre prénom",
        required: true,
        options: [],
      },
      {
        id: "field_2",
        type: "text",
        label: "Nom",
        name: "lastName",
        placeholder: "Votre nom",
        required: true,
        options: [],
      },
      {
        id: "field_3",
        type: "text",
        label: "Adresse de livraison",
        name: "deliveryAddress",
        placeholder: "Votre adresse de livraison",
        required: true,
        options: [],
      },
      {
        id: "field_4",
        type: "text",
        label: "Numéro de téléphone",
        name: "phoneNumber",
        placeholder: "Votre numéro de téléphone",
        required: false,
        options: [],
      },
      {
        id: "field_5",
        type: "email",
        label: "Email",
        name: "email",
        placeholder: "Votre adresse email",
        required: false,
        options: [],
      },
      {
        id: "field_6",
        type: "select",
        label: "Type de commande",
        name: "orderType",
        placeholder: "Sélectionnez le type de commande",
        required: false,
        options: ["Sur place", "À emporter", "Livraison"],
      },
      {
        id: "field_7",
        type: "textarea",
        label: "Allergies ou restrictions alimentaires",
        name: "dietaryRestrictions",
        placeholder: "Indiquez vos allergies ou restrictions alimentaires",
        required: false,
        options: [],
      },
    ],
  },
  "4111": {
    id: "form_4111",
    fields: [
      {
        id: "field_1",
        type: "text",
        label: "Prénom",
        name: "firstName",
        placeholder: "Votre prénom",
        required: true,
        options: [],
      },
      {
        id: "field_2",
        type: "text",
        label: "Nom",
        name: "lastName",
        placeholder: "Votre nom",
        required: true,
        options: [],
      },
      {
        id: "field_3",
        type: "text",
        label: "Adresse de livraison",
        name: "deliveryAddress",
        placeholder: "Votre adresse de livraison",
        required: true,
        options: [],
      },
      {
        id: "field_4",
        type: "text",
        label: "Numéro de téléphone",
        name: "phoneNumber",
        placeholder: "Votre numéro de téléphone",
        required: false,
        options: [],
      },
      {
        id: "field_5",
        type: "email",
        label: "Email",
        name: "email",
        placeholder: "Votre adresse email",
        required: false,
        options: [],
      },
      {
        id: "field_6",
        type: "select",
        label: "Type de transport",
        name: "transportType",
        placeholder: "Sélectionnez le type de transport",
        required: false,
        options: ["Bus", "Train", "Métro", "Tramway"],
      },
      {
        id: "field_7",
        type: "text",
        label: "Point de départ",
        name: "departurePoint",
        placeholder: "Votre point de départ",
        required: false,
        options: [],
      },
      {
        id: "field_8",
        type: "text",
        label: "Point d'arrivée",
        name: "arrivalPoint",
        placeholder: "Votre point d'arrivée",
        required: false,
        options: [],
      },
    ],
  },
  "5999": {
    id: "form_5999",
    fields: [
      {
        id: "field_1",
        type: "text",
        label: "Prénom",
        name: "firstName",
        placeholder: "Votre prénom",
        required: true,
        options: [],
      },
      {
        id: "field_2",
        type: "text",
        label: "Nom",
        name: "lastName",
        placeholder: "Votre nom",
        required: true,
        options: [],
      },
      {
        id: "field_3",
        type: "text",
        label: "Adresse de livraison",
        name: "deliveryAddress",
        placeholder: "Votre adresse de livraison",
        required: true,
        options: [],
      },
      {
        id: "field_4",
        type: "text",
        label: "Numéro de téléphone",
        name: "phoneNumber",
        placeholder: "Votre numéro de téléphone",
        required: false,
        options: [],
      },
      {
        id: "field_5",
        type: "email",
        label: "Email",
        name: "email",
        placeholder: "Votre adresse email",
        required: false,
        options: [],
      },
      {
        id: "field_6",
        type: "text",
        label: "Code postal",
        name: "postalCode",
        placeholder: "Votre code postal",
        required: false,
        options: [],
      },
      {
        id: "field_7",
        type: "select",
        label: "Type de produit",
        name: "productType",
        placeholder: "Sélectionnez le type de produit",
        required: false,
        options: ["Électronique", "Vêtements", "Accessoires", "Autre"],
      },
    ],
  },
  "4789": {
    id: "form_4789",
    fields: [
      {
        id: "field_1",
        type: "text",
        label: "Prénom",
        name: "firstName",
        placeholder: "Votre prénom",
        required: true,
        options: [],
      },
      {
        id: "field_2",
        type: "text",
        label: "Nom",
        name: "lastName",
        placeholder: "Votre nom",
        required: true,
        options: [],
      },
      {
        id: "field_3",
        type: "text",
        label: "Adresse de livraison",
        name: "deliveryAddress",
        placeholder: "Votre adresse de livraison",
        required: true,
        options: [],
      },
      {
        id: "field_4",
        type: "text",
        label: "Numéro de téléphone",
        name: "phoneNumber",
        placeholder: "Votre numéro de téléphone",
        required: false,
        options: [],
      },
      {
        id: "field_5",
        type: "email",
        label: "Email",
        name: "email",
        placeholder: "Votre adresse email",
        required: false,
        options: [],
      },
      {
        id: "field_6",
        type: "select",
        label: "Type de service",
        name: "serviceType",
        placeholder: "Sélectionnez le type de service",
        required: false,
        options: [
          "Livraison",
          "Transport de marchandises",
          "Service express",
          "Autre",
        ],
      },
      {
        id: "field_7",
        type: "textarea",
        label: "Instructions spéciales",
        name: "specialInstructions",
        placeholder: "Indiquez vos instructions spéciales",
        required: false,
        options: [],
      },
    ],
  },
};
